DROP DATABASE IF EXISTS orderdb;
DROP USER IF EXISTS `useradmin`@`%`;
DROP USER IF EXISTS `customer`@`%`;
CREATE DATABASE IF NOT EXISTS orderdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `useradmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `orderdb`.* TO `useradmin`@`%`;
CREATE USER IF NOT EXISTS `customer`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `orderdb`.* TO `customer`@`%`;
FLUSH PRIVILEGES;